backend:
  name: git-gateway
  branch: main # Change this if using a different branch

media_library:
  name: uploadcare
  config:
    publicKey: "your-public-key"

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
